{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "string yo\n",
      "9487.0\n",
      "True\n",
      "0\n",
      "True\n"
     ]
    }
   ],
   "source": [
    "message=\"string yo\"\n",
    "size=9487\n",
    "percentage=0.8\n",
    "momis=True\n",
    "print(message)\n",
    "print (float(size))\n",
    "print (str(momis))\n",
    "print (int(percentage))\n",
    "print (bool(message))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "C\n"
     ]
    }
   ],
   "source": [
    "num=70\n",
    "if num>=90 :\n",
    "    print('A')\n",
    "elif 90>num>=80:\n",
    "    print('B')\n",
    "elif 80>num>=70:\n",
    "    print('C')\n",
    "elif 70>num>=60:\n",
    "    print('D')\n",
    "else:\n",
    "    print('F')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0\n",
      "1\n",
      "2\n",
      "3\n",
      "4\n",
      "5\n",
      "6\n",
      "7\n",
      "8\n",
      "9\n"
     ]
    }
   ],
   "source": [
    "count=0\n",
    "while (count<10):\n",
    "    print (count)\n",
    "    count=count+1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3\n",
      "4\n",
      "5\n",
      "6\n"
     ]
    }
   ],
   "source": [
    "for i in range (3,7):\n",
    "    print(i)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "even\n",
      "6\n",
      "odd\n",
      "55\n",
      "odd\n",
      "91\n"
     ]
    }
   ],
   "source": [
    "def oddeven(answers):\n",
    "    for answer in answers: \n",
    "        start= 0\n",
    "        for i in range (1,answer+1):\n",
    "            start=start+ i\n",
    "        if start%2==1:\n",
    "            print(\"odd\")\n",
    "        else:\n",
    "            print(\"even\")\n",
    "        print(start)\n",
    "answers=[3,10,13]\n",
    "oddeven(answers)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\users\\james\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\ipykernel_launcher.py:9: DeprecationWarning: use options instead of chrome_options\n",
      "  if __name__ == '__main__':\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "微軟表態爭取合作，願提供美軍雲端運算科技\n",
      "2018 年 10 月 27 日 17:01 \n",
      "Microsoft,雲端\n",
      "日本全家突圍，零售業勢力掀重整潮\n",
      "2018 年 10 月 27 日 0:00 \n",
      "財經,電子商務\n",
      "Facebook 要推出短影片應用 Lasso，以緩解青少年用戶流失\n",
      "2018 年 10 月 26 日 16:30 \n",
      "app,Facebook,社群\n",
      "iPhone XR 在台開賣！中華電：首波供貨不如預期，eSIM 將完成測試\n",
      "2018 年 10 月 26 日 13:15 \n",
      "Apple,iPhone,網路\n",
      "Facebook 因劍橋分析資料洩露一案被英國罰 50 萬英鎊\n",
      "2018 年 10 月 26 日 12:12 \n",
      "Facebook,網路,資訊安全\n",
      "Facebook 維護台灣選舉公信力，設跨部門專案小組\n",
      "2018 年 10 月 26 日 10:00 \n",
      "Facebook,數位內容,社群\n",
      "5G 基地台合作又一樁？富士通傳找上愛立信簽備忘錄\n",
      "2018 年 10 月 26 日 9:15 \n",
      "網路,網通設備\n",
      "不到 200 天，騰訊《絕地求生》手遊總營收突破 1 億美元\n",
      "2018 年 10 月 26 日 9:00 \n",
      "手機,網路,遊戲軟體\n",
      "微軟 Azure 雲端服務成長開始趨緩，但納德拉似乎不擔心\n",
      "2018 年 10 月 26 日 8:45 \n",
      "AI 人工智慧,Microsoft,財報\n",
      "Uber 衝擊 1,000 億美元估值，目標直指交通界的 Amazon\n",
      "2018 年 10 月 26 日 8:30 \n",
      "共享經濟,網路,財經\n",
      "本有機會成為世界首富的人，想幫你把資料從科技公司手中奪回來\n",
      "2018 年 10 月 26 日 8:15 \n",
      "名人談,科技史,科技教育\n",
      "YouTube 成立 Learning 基金投資 2 千萬美元扶持教育影片，是看好線上教育嗎？\n",
      "2018 年 10 月 26 日 7:30 \n",
      "Google,數位內容,社群\n",
      "叫陣 Amazon、阿里巴巴強打雲端優勢，微軟在上海開發者大會宣誓帶中國企業走向國際\n",
      "2018 年 10 月 25 日 21:39 \n",
      "Microsoft,中國觀察,雲端\n",
      "從商品、行銷、物流、創新各面向布局就緒！PChome 全面迎接雙 11，挑戰業績翻倍成長\n",
      "2018 年 10 月 25 日 18:45 \n",
      "網路,電子商務\n",
      "內容巨擘不讓 Netflix 獨大，串流媒體黃金時代結束\n",
      "2018 年 10 月 25 日 14:20 \n",
      "數位內容,網路\n",
      "國泰航空系統遭入侵，940 萬名乘客資料遭不當讀取\n",
      "2018 年 10 月 25 日 13:52 \n",
      "網路,資訊安全\n",
      "LINE Corp 創史上最低收盤：Q3 盈轉虧、行銷費用暴增\n",
      "2018 年 10 月 25 日 12:30 \n",
      "手機,網路,財經\n",
      "貿易戰諜對諜，傳川普私人 iPhone 遭中國竊聽\n",
      "2018 年 10 月 25 日 12:00 \n",
      "iPhone,中國觀察,資訊安全\n",
      "華為成立德國實驗室屬實，但並非為 5G 牌照\n",
      "2018 年 10 月 25 日 8:30 \n",
      "網路,網通設備\n",
      "把隱私決定權交還使用者！Google 開放刪除搜尋紀錄\n",
      "2018 年 10 月 25 日 8:27 \n",
      "Google,網路,資訊安全\n",
      "5G 手機 2019 年問世，網通廠準備迎商機\n",
      "2018 年 10 月 24 日 14:30 \n",
      "手機,網路,網通設備\n",
      "華為新機對美國市場喊暫停，Mate 20 將不會在美銷售\n",
      "2018 年 10 月 24 日 13:00 \n",
      "手機,晶片,資訊安全\n",
      "Instagram 險勝 Snapchat，首度躍居美青少年最常使用社群平台\n",
      "2018 年 10 月 24 日 12:45 \n",
      "社群,網路\n",
      "蘋果決戰 Netflix，傳媒體串流服務 2019 年上線\n",
      "2018 年 10 月 24 日 12:30 \n",
      "Apple,數位內容,網路\n",
      "網友開發「PTT 網軍作息程式」，輸入 PTT ID 就可以輔助判斷誰是網軍（異常鄉民使用者）\n",
      "2018 年 10 月 24 日 11:20 \n",
      "社群,網路,網路趣聞\n",
      "Messenger 全面改版，走簡潔風\n",
      "2018 年 10 月 24 日 11:00 \n",
      "app,Facebook,社群\n",
      "依靠競價搜尋，蘋果 App Store 廣告收入 2020 年或達到 20 億美元\n",
      "2018 年 10 月 24 日 8:45 \n",
      "Apple,數位廣告,網路\n",
      "阿里巴巴雲端服務進軍歐洲市場，兩個倫敦資料中心開始營運\n",
      "2018 年 10 月 24 日 8:30 \n",
      "網路,雲端\n",
      "中國出手監管區塊鏈服務，實名制將讓匿名特色盪然無存\n",
      "2018 年 10 月 24 日 8:00 \n",
      "中國觀察,區塊鏈 Blockchain,資訊安全\n",
      "開支不斷增加，Netflix 發行 20 億美元債券補救\n",
      "2018 年 10 月 24 日 7:30 \n",
      "數位內容,財經\n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "import os\n",
    "options= Options()\n",
    "options.add_argument('--headless')\n",
    "options.add_argument('--disable-gpu')\n",
    "driver=webdriver.Chrome(os.getcwd()+\"/chromedriver\",chrome_options=options)\n",
    "\n",
    "for i in range(1,3):\n",
    "    pagenumber=str(i)\n",
    "    driver.get('https://technews.tw/category/internet/page/'+pagenumber)\n",
    "    time.sleep(0.5)\n",
    "    sourceCode=BeautifulSoup(driver.page_source,\"html.parser\")\n",
    "    headers=sourceCode.find_all(\"header\",\"entry-header\")\n",
    "    for header in headers:\n",
    "        sourceCode2=BeautifulSoup(str(header),\"html.parser\")\n",
    "        title=sourceCode2.find_all(\"h1\",\"entry-title\")[0].text\n",
    "        print(title)\n",
    "        date=sourceCode2.find_all(\"span\",\"body\")[1].text\n",
    "        print(date)\n",
    "        category=sourceCode2.find_all(\"span\",\"body\")[2]\n",
    "        sourceCode3=BeautifulSoup(str(category),\"html.parser\")\n",
    "        typs=sourceCode3.find_all(\"a\")\n",
    "        keywords=\"\"\n",
    "        for typ in typs:\n",
    "            if typ==typs[-1]:\n",
    "                keywords=keywords+typ.text\n",
    "            else:\n",
    "                keywords=keywords+typ.text+\",\"\n",
    "        print(keywords)\n",
    "driver.quit()\n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\users\\james\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\ipykernel_launcher.py:9: DeprecationWarning: use options instead of chrome_options\n",
      "  if __name__ == '__main__':\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "iRobot 將地圖數據共享給了 Google，它會是好隊友嗎？\n",
      "2018 年 11 月 04 日 12:00 \n",
      "Google,機器人,網路\n",
      "https://technews.tw/2018/11/04/irobot-shared-map-data-to-google/\n",
      "據外媒報導， Google 和 iRobot 對外公布，雙方正在就智慧家居方面相關技術進行合作──利用 iRobot 掃地機器人（Roomba i7+）收集的地圖數據，改進智慧家居相關技術。 繼續閱讀.. \n",
      "微軟 CEO 納德拉：數位時代需要讓捍衛人權一樣捍衛隱私\n",
      "2018 年 11 月 03 日 9:22 \n",
      "Microsoft,網路,資訊安全\n",
      "https://technews.tw/2018/11/03/microsoft-ceo-satya-nadella-tech-companies-need-to-defend-privacy-as-a-human-right/\n",
      "在歐盟頒布最嚴隱私保護法後，各大科技公司紛紛表態將更嚴格地按照法案的要求執行，一筆筆金額巨大的罰單開出，科技巨頭也面臨著巨大的壓力，微軟公司執行長薩蒂亞·納德拉（Satya Nadella）在倫敦表示，科技產業需要與政府機構合作，考慮到每個公司都數位化後帶來的影響，其中隱私、網路安全和人工智慧倫理道德是 3 個最重要的隱私，每一家提供網路服務的公司都應該講用戶隱私視為人權。 繼續閱讀.. \n",
      "貢獻 Github 最多最愛 Linux 的微軟，潘正磊要大家聽其言觀其行證明開源的心\n",
      "2018 年 11 月 02 日 17:23 \n",
      "Microsoft,社群\n",
      "https://technews.tw/2018/11/02/microsoft-love-linux-and-contributed-most-julia-liuson-want-us-to-obersvate-words-and-action-for-open-source/\n",
      "微軟有長期敵視 Linux 和開源的過往歷史，如今因為要擁抱開發者而積極投入開源，用開源方式釋出開發工具 Visual Studio Code，最近則是併購社程式碼代管服務 Github。負責微軟開發工具開發 Visual Studio 的潘正磊以 CEO Satelly 的話回應外界對 Github 收購一事，指出不要用過去眼光看微軟，而是看微軟近期的實際行動。 繼續閱讀.. \n",
      "菜鳥網絡智能物流升級迎 2018 天貓雙 11，智能倉庫啟動 700 台 AGV\n",
      "2018 年 11 月 02 日 17:00 \n",
      "物聯網,網路,電子商務\n",
      "https://technews.tw/2018/11/02/cainiao-ready-for-2018-11-11-global-shopping-festival/\n",
      "為迎接 2018 天貓雙 11 全球狂歡節的物流高峰，阿里巴巴集團旗下的物流公司菜鳥網絡全面提升物流科技，在中國的機器人智慧倉庫近期投入營運，同時打造更強大的末端配送服務；在跨境物流方面，已預留大量貨櫃與包機，力求把包裹快速送達全球各地，進一步鞏固新物流與跨境物流能力。\n",
      "Flickr 緊縮照片數量，台灣開源社群面臨數位遺跡保存危機\n",
      "2018 年 11 月 02 日 15:30 \n",
      "社群\n",
      "https://technews.tw/2018/11/02/flickr-open-source-photo-crisis/\n",
      "Flickr 開始依據其母公司的策略，恢復原先的付費會員方案，引起相當大的恐慌。曾任社群開源活動，SITCON 學生計算機年會總召的 Denny Huang，發文提醒台灣各個開源大會的參與者，有照片放在 Flickr 的話，要開始繳年繳 49.99 美元的年費，不然就會有 1,000 的上限，超過部分將依舊時間先後，新的照片將被移除。 繼續閱讀.. \n",
      "購併之後彰顯紅帽的經營之道，2018 年是開源之年\n",
      "2018 年 11 月 02 日 14:52 \n",
      "雲端\n",
      "https://technews.tw/2018/11/02/purchage-redhat-proof-that-2018-is-the-year-of-open-source/\n",
      "IBM 收購紅帽震驚業界，合併後紅帽是否能維繫原先的組織文化，用開源開放的方式開發產品還有提供服務不無疑問。在 2018 紅帽論壇上面，紅帽亞洲區成長與新興市場副總裁暨總經理黃育樂對外宣誓，在 IBM 下面的紅帽會以獨立單位運作，並且維繫原先開放的公司文化，提供合作伙伴具備創新價值的方案。 繼續閱讀.. \n",
      "虛擬銀行 Monzo 再獲新資金，晉身獨角獸行列\n",
      "2018 年 11 月 02 日 14:00 \n",
      "Fintech,新創,網路\n",
      "https://technews.tw/2018/11/02/british-app-bank-monzo-hits-unicorn-status-after-latest-fund-raising/\n",
      "近年傳統銀行經營模式隨著用戶習慣改變，也起了不少變化，規模更彈性的英國虛擬銀行 Monzo 最近得到 8,500 萬英鎊融資，估值達 10 億英鎊，躋身獨角獸行列。 繼續閱讀.. \n",
      "17 Media 與華視打造即時互動新聞，觀看流量攀升 3 成\n",
      "2018 年 11 月 02 日 11:15 \n",
      "社群,網路,電子娛樂\n",
      "https://technews.tw/2018/11/02/17-media-and-chinese-television-system/\n",
      "17 Media 與華視攜手合作的「華視 17 報新聞」，邀請到新聞主播陳子見以及 4 位超人氣直播主為觀眾主持新聞節目。透過節目中的「即時民調」與「下節新聞選播」功能，據 17 Media 內部數據顯示，華視 17 報新聞開播 15 天創下即時留言數逾 10 萬則，觀看流量比當月同時段攀升 3 成，新型態的互動新聞讓觀眾更近一步與新聞製作團隊即時互動。\n",
      "Flickr 重大改版：終止 1TB 免費空間改為 1,000 張照片！2/5 後將自動刪圖片\n",
      "2018 年 11 月 02 日 7:19 \n",
      "數位內容,網路\n",
      "https://technews.tw/2018/11/02/flickr-will-end-1tb-of-free-storage-and-limit-free-users-to-1000-photos/\n",
      "曾經是全球最大的相簿平台 Flickr，在賣給 SmugMug 後，該來的改革還是來了，而這項改革可能會從此改變 Flickr 的地位。Flickr 宣布重大改版，將從 2019 年 1 月終止免費用戶的 1TB 容量，改為免費 1,000 張影片或照片，但大砍免費服務的同時，另一方面也會大幅升級專業版用戶的服務。\n",
      "趨勢科技：台灣企業應多重視 OT 的與時俱進和資安防護\n",
      "2018 年 11 月 01 日 18:55 \n",
      "資訊安全\n",
      "https://technews.tw/2018/11/01/trendmicro-says-taiwan-enterprise-should-be-more-force-on-protecting-of-operation-technology-and-make-it-up-to-date/\n",
      "不少公司為了公司長久的成長，引入更多資訊科技，進行公司的數位轉型。越來越多公司將傳統不會連上網路的設備接上網路，對轉型的公司是機會，也是駭客的機會，有更多能攻擊的裝置，而且是攸關企業營運的關鍵設備。趨勢科技認為企業該好好重視營運科技 OT 的防護，並且要能隨著新技術發展跟上腳步。 繼續閱讀.. \n",
      "創辦團隊憤而離職後，WhatsApp 即將掛上廣告版面\n",
      "2018 年 11 月 01 日 17:04 \n",
      "Facebook,數位廣告,社群\n",
      "https://technews.tw/2018/11/01/ads-in-whatsapp-are-coming/\n",
      "WhatsApp 是全球用戶最多的即時通訊服務之一，最大的特點就是提供簡單、快捷且加密的通訊服務，以用戶付費為主要商業模式，經過十年營運，WhatsApp 備受好評的無廣告模式或許很快將走向終結。WhatsApp 部門副總裁 Chris Daniels 透露，WhatsApp 的 Status 功能很快就會加入廣告服務。 繼續閱讀.. \n",
      "聯發科布局芬蘭，搶進 5G 卡位 6G\n",
      "2018 年 11 月 01 日 15:40 \n",
      "晶片,網路,網通設備\n",
      "https://technews.tw/2018/11/01/mediatek-layout-finland-grab-5g-card-6g/\n",
      "聯發科為了強化通訊晶片業務，在 4 年前建立了芬蘭研發中心，如今更與奧盧（Oulu）大學進行建教合作，培育新人才。\n",
      "14 家跨境電商未辦稅籍登記，國稅局研議開罰\n",
      "2018 年 11 月 01 日 15:30 \n",
      "科技政策,電子商務\n",
      "https://technews.tw/2018/11/01/14-cross-border-e-commerce-companies-dont-pay-tax/\n",
      "台北國稅局表示，截至 10 月 25 日，已受理 94 家境外電商申請核准辦理稅籍登記，但發現有 14 家跨境電商應登記卻未登記，現正蒐集金流資料，與法務部及 NCC 研議開罰方式。 繼續閱讀.. \n",
      "台灣活躍的公民科技社群，是否是尋找避風港的國際媒體應許地？\n",
      "2018 年 11 月 01 日 10:32 \n",
      "社群,資訊安全\n",
      "https://technews.tw/2018/11/01/the-active-civil-tech-community-in-taiwan-will-it-be-the-shelter-for-international-media/\n",
      "台灣的公民科技社群相當活躍，從十幾年前的開源大會 COSCUP 仍屹立不搖，到辦了幾次的 g0v Summit 雙年大會，聚集台灣海內外的參與者。而近期香港政府駁回駐外記者的居留申請，已經預示做為不少國際媒體駐地的香港，難以繼續維持以往享有的新聞自由。那這時候，有充分新聞自由的台灣，也許是駐地在香港的國際媒體，能夠轉移陣地的地方。 繼續閱讀.. \n",
      "面臨用戶停滯危機，Facebook 限時動態會是下一個成長點？\n",
      "2018 年 11 月 01 日 8:00 \n",
      "Facebook,社群,資訊安全\n",
      "https://technews.tw/2018/11/01/facebook-stories-growth-point/\n",
      "先前美國投資及資產管理公司 Piper Jaffray 公布了一份報告，顯示每個月至少使用一次 Facebook 的青少年比率，已經從 2016 年秋季的 52%，掉到 36%。不只在青少年市場失勢，根據第三季財報，Facebook 每月活躍用戶成長沒能達標，營收更出現近 6 年來最緩慢成長，甚至還提前打了預防針，暗示明年的支出還會再增加。 繼續閱讀.. \n",
      "iRobot 將地圖數據共享給了 Google，它會是好隊友嗎？\n",
      "2018 年 11 月 04 日 12:00 \n",
      "Google,機器人,網路\n",
      "https://technews.tw/2018/11/04/irobot-shared-map-data-to-google/\n",
      "據外媒報導， Google 和 iRobot 對外公布，雙方正在就智慧家居方面相關技術進行合作──利用 iRobot 掃地機器人（Roomba i7+）收集的地圖數據，改進智慧家居相關技術。 繼續閱讀.. \n",
      "微軟 CEO 納德拉：數位時代需要讓捍衛人權一樣捍衛隱私\n",
      "2018 年 11 月 03 日 9:22 \n",
      "Microsoft,網路,資訊安全\n",
      "https://technews.tw/2018/11/03/microsoft-ceo-satya-nadella-tech-companies-need-to-defend-privacy-as-a-human-right/\n",
      "在歐盟頒布最嚴隱私保護法後，各大科技公司紛紛表態將更嚴格地按照法案的要求執行，一筆筆金額巨大的罰單開出，科技巨頭也面臨著巨大的壓力，微軟公司執行長薩蒂亞·納德拉（Satya Nadella）在倫敦表示，科技產業需要與政府機構合作，考慮到每個公司都數位化後帶來的影響，其中隱私、網路安全和人工智慧倫理道德是 3 個最重要的隱私，每一家提供網路服務的公司都應該講用戶隱私視為人權。 繼續閱讀.. \n",
      "貢獻 Github 最多最愛 Linux 的微軟，潘正磊要大家聽其言觀其行證明開源的心\n",
      "2018 年 11 月 02 日 17:23 \n",
      "Microsoft,社群\n",
      "https://technews.tw/2018/11/02/microsoft-love-linux-and-contributed-most-julia-liuson-want-us-to-obersvate-words-and-action-for-open-source/\n",
      "微軟有長期敵視 Linux 和開源的過往歷史，如今因為要擁抱開發者而積極投入開源，用開源方式釋出開發工具 Visual Studio Code，最近則是併購社程式碼代管服務 Github。負責微軟開發工具開發 Visual Studio 的潘正磊以 CEO Satelly 的話回應外界對 Github 收購一事，指出不要用過去眼光看微軟，而是看微軟近期的實際行動。 繼續閱讀.. \n",
      "菜鳥網絡智能物流升級迎 2018 天貓雙 11，智能倉庫啟動 700 台 AGV\n",
      "2018 年 11 月 02 日 17:00 \n",
      "物聯網,網路,電子商務\n",
      "https://technews.tw/2018/11/02/cainiao-ready-for-2018-11-11-global-shopping-festival/\n",
      "為迎接 2018 天貓雙 11 全球狂歡節的物流高峰，阿里巴巴集團旗下的物流公司菜鳥網絡全面提升物流科技，在中國的機器人智慧倉庫近期投入營運，同時打造更強大的末端配送服務；在跨境物流方面，已預留大量貨櫃與包機，力求把包裹快速送達全球各地，進一步鞏固新物流與跨境物流能力。\n",
      "Flickr 緊縮照片數量，台灣開源社群面臨數位遺跡保存危機\n",
      "2018 年 11 月 02 日 15:30 \n",
      "社群\n",
      "https://technews.tw/2018/11/02/flickr-open-source-photo-crisis/\n",
      "Flickr 開始依據其母公司的策略，恢復原先的付費會員方案，引起相當大的恐慌。曾任社群開源活動，SITCON 學生計算機年會總召的 Denny Huang，發文提醒台灣各個開源大會的參與者，有照片放在 Flickr 的話，要開始繳年繳 49.99 美元的年費，不然就會有 1,000 的上限，超過部分將依舊時間先後，新的照片將被移除。 繼續閱讀.. \n",
      "購併之後彰顯紅帽的經營之道，2018 年是開源之年\n",
      "2018 年 11 月 02 日 14:52 \n",
      "雲端\n",
      "https://technews.tw/2018/11/02/purchage-redhat-proof-that-2018-is-the-year-of-open-source/\n",
      "IBM 收購紅帽震驚業界，合併後紅帽是否能維繫原先的組織文化，用開源開放的方式開發產品還有提供服務不無疑問。在 2018 紅帽論壇上面，紅帽亞洲區成長與新興市場副總裁暨總經理黃育樂對外宣誓，在 IBM 下面的紅帽會以獨立單位運作，並且維繫原先開放的公司文化，提供合作伙伴具備創新價值的方案。 繼續閱讀.. \n",
      "虛擬銀行 Monzo 再獲新資金，晉身獨角獸行列\n",
      "2018 年 11 月 02 日 14:00 \n",
      "Fintech,新創,網路\n",
      "https://technews.tw/2018/11/02/british-app-bank-monzo-hits-unicorn-status-after-latest-fund-raising/\n",
      "近年傳統銀行經營模式隨著用戶習慣改變，也起了不少變化，規模更彈性的英國虛擬銀行 Monzo 最近得到 8,500 萬英鎊融資，估值達 10 億英鎊，躋身獨角獸行列。 繼續閱讀.. \n",
      "17 Media 與華視打造即時互動新聞，觀看流量攀升 3 成\n",
      "2018 年 11 月 02 日 11:15 \n",
      "社群,網路,電子娛樂\n",
      "https://technews.tw/2018/11/02/17-media-and-chinese-television-system/\n",
      "17 Media 與華視攜手合作的「華視 17 報新聞」，邀請到新聞主播陳子見以及 4 位超人氣直播主為觀眾主持新聞節目。透過節目中的「即時民調」與「下節新聞選播」功能，據 17 Media 內部數據顯示，華視 17 報新聞開播 15 天創下即時留言數逾 10 萬則，觀看流量比當月同時段攀升 3 成，新型態的互動新聞讓觀眾更近一步與新聞製作團隊即時互動。\n",
      "Flickr 重大改版：終止 1TB 免費空間改為 1,000 張照片！2/5 後將自動刪圖片\n",
      "2018 年 11 月 02 日 7:19 \n",
      "數位內容,網路\n",
      "https://technews.tw/2018/11/02/flickr-will-end-1tb-of-free-storage-and-limit-free-users-to-1000-photos/\n",
      "曾經是全球最大的相簿平台 Flickr，在賣給 SmugMug 後，該來的改革還是來了，而這項改革可能會從此改變 Flickr 的地位。Flickr 宣布重大改版，將從 2019 年 1 月終止免費用戶的 1TB 容量，改為免費 1,000 張影片或照片，但大砍免費服務的同時，另一方面也會大幅升級專業版用戶的服務。\n",
      "趨勢科技：台灣企業應多重視 OT 的與時俱進和資安防護\n",
      "2018 年 11 月 01 日 18:55 \n",
      "資訊安全\n",
      "https://technews.tw/2018/11/01/trendmicro-says-taiwan-enterprise-should-be-more-force-on-protecting-of-operation-technology-and-make-it-up-to-date/\n",
      "不少公司為了公司長久的成長，引入更多資訊科技，進行公司的數位轉型。越來越多公司將傳統不會連上網路的設備接上網路，對轉型的公司是機會，也是駭客的機會，有更多能攻擊的裝置，而且是攸關企業營運的關鍵設備。趨勢科技認為企業該好好重視營運科技 OT 的防護，並且要能隨著新技術發展跟上腳步。 繼續閱讀.. \n",
      "創辦團隊憤而離職後，WhatsApp 即將掛上廣告版面\n",
      "2018 年 11 月 01 日 17:04 \n",
      "Facebook,數位廣告,社群\n",
      "https://technews.tw/2018/11/01/ads-in-whatsapp-are-coming/\n",
      "WhatsApp 是全球用戶最多的即時通訊服務之一，最大的特點就是提供簡單、快捷且加密的通訊服務，以用戶付費為主要商業模式，經過十年營運，WhatsApp 備受好評的無廣告模式或許很快將走向終結。WhatsApp 部門副總裁 Chris Daniels 透露，WhatsApp 的 Status 功能很快就會加入廣告服務。 繼續閱讀.. \n",
      "聯發科布局芬蘭，搶進 5G 卡位 6G\n",
      "2018 年 11 月 01 日 15:40 \n",
      "晶片,網路,網通設備\n",
      "https://technews.tw/2018/11/01/mediatek-layout-finland-grab-5g-card-6g/\n",
      "聯發科為了強化通訊晶片業務，在 4 年前建立了芬蘭研發中心，如今更與奧盧（Oulu）大學進行建教合作，培育新人才。\n",
      "14 家跨境電商未辦稅籍登記，國稅局研議開罰\n",
      "2018 年 11 月 01 日 15:30 \n",
      "科技政策,電子商務\n",
      "https://technews.tw/2018/11/01/14-cross-border-e-commerce-companies-dont-pay-tax/\n",
      "台北國稅局表示，截至 10 月 25 日，已受理 94 家境外電商申請核准辦理稅籍登記，但發現有 14 家跨境電商應登記卻未登記，現正蒐集金流資料，與法務部及 NCC 研議開罰方式。 繼續閱讀.. \n",
      "台灣活躍的公民科技社群，是否是尋找避風港的國際媒體應許地？\n",
      "2018 年 11 月 01 日 10:32 \n",
      "社群,資訊安全\n",
      "https://technews.tw/2018/11/01/the-active-civil-tech-community-in-taiwan-will-it-be-the-shelter-for-international-media/\n",
      "台灣的公民科技社群相當活躍，從十幾年前的開源大會 COSCUP 仍屹立不搖，到辦了幾次的 g0v Summit 雙年大會，聚集台灣海內外的參與者。而近期香港政府駁回駐外記者的居留申請，已經預示做為不少國際媒體駐地的香港，難以繼續維持以往享有的新聞自由。那這時候，有充分新聞自由的台灣，也許是駐地在香港的國際媒體，能夠轉移陣地的地方。 繼續閱讀.. \n",
      "面臨用戶停滯危機，Facebook 限時動態會是下一個成長點？\n",
      "2018 年 11 月 01 日 8:00 \n",
      "Facebook,社群,資訊安全\n",
      "https://technews.tw/2018/11/01/facebook-stories-growth-point/\n",
      "先前美國投資及資產管理公司 Piper Jaffray 公布了一份報告，顯示每個月至少使用一次 Facebook 的青少年比率，已經從 2016 年秋季的 52%，掉到 36%。不只在青少年市場失勢，根據第三季財報，Facebook 每月活躍用戶成長沒能達標，營收更出現近 6 年來最緩慢成長，甚至還提前打了預防針，暗示明年的支出還會再增加。 繼續閱讀.. \n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "import os\n",
    "options= Options()\n",
    "options.add_argument('--headless')\n",
    "options.add_argument('--disable-gpu')\n",
    "driver=webdriver.Chrome(os.getcwd()+\"/chromedriver\",chrome_options=options)\n",
    "\n",
    "for i in range(1,3):\n",
    "    driver.get('https://technews.tw/category/internet/page/1')\n",
    "    time.sleep(0.5)\n",
    "    sourceCode=BeautifulSoup(driver.page_source,\"html.parser\")\n",
    "    contents=sourceCode.find_all(\"div\",\"content\")\n",
    "    for content in contents:\n",
    "        sourceCode2=BeautifulSoup(str(content),\"html.parser\")\n",
    "        title=sourceCode2.find_all(\"h1\",\"entry-title\")[0].text\n",
    "        print(title)\n",
    "        date=sourceCode2.find_all(\"span\",\"body\")[1].text\n",
    "        print(date)\n",
    "        category=sourceCode2.find_all(\"span\",\"body\")[2]\n",
    "        sourceCode3=BeautifulSoup(str(category),\"html.parser\")\n",
    "        typs=sourceCode3.find_all(\"a\")\n",
    "        keywords=\"\"\n",
    "        for typ in typs:\n",
    "            if typ==typs[-1]:\n",
    "                keywords=keywords+typ.text\n",
    "            else:\n",
    "                keywords=keywords+typ.text+\",\"\n",
    "        print(keywords)\n",
    "        links=sourceCode2.find_all(\"a\",href=True)[0]['href']\n",
    "        print(links)\n",
    "        pretext=sourceCode2.find_all(\"p\")[0]\n",
    "        print(pretext)\n",
    "driver.quit()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "metadata": {
    "scrolled": false
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\users\\james\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\ipykernel_launcher.py:9: DeprecationWarning: use options instead of chrome_options\n",
      "  if __name__ == '__main__':\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[轉錄][分享] League Of Legends 熱鍵以及指令 …\n",
      "ric917\n",
      " 3/04\n",
      "86\n",
      "[分享] League of Legends  英雄　Nasus\n",
      "HEINOUS\n",
      " 3/04\n",
      "87\n",
      "[心得] 英雄-Nidalee 叢林女王!\n",
      "errard\n",
      " 3/04\n",
      "88\n",
      "[分享]League of Legends 台灣TS伺服器\n",
      "elenore\n",
      " 3/04\n",
      "86\n",
      "[心得] 整理 台灣LOL集散地\n",
      "TCBeliever\n",
      " 3/04\n",
      "87\n",
      "[週報] LoL週報 No. 1 (0302-0304)\n",
      "Dolacone\n",
      " 3/04\n",
      "88\n",
      "[分享] League of Legends FAQ\n",
      "Dolacone\n",
      " 3/04\n",
      "86\n",
      "[英雄] Nidalee 來自森林的支援者  AP流\n",
      "heerofang\n",
      " 3/05\n",
      "87\n",
      "[無用] 官網紅帖 Matchmaking Improvements Up …\n",
      "errard\n",
      " 3/05\n",
      "88\n",
      "[閒聊] 新帳號陪伴等級20以下的新手出去打仗\n",
      "nyc1960\n",
      " 3/05\n",
      "86\n",
      "[創作] 進版  戰吧 鄉民們\n",
      "kent550079\n",
      " 3/05\n",
      "87\n",
      "[英雄] Twitch - the Creepy Little Mouse\n",
      "SamMa\n",
      " 3/06\n",
      "88\n",
      "[英雄] Twitch - 戰前準備\n",
      "SamMa\n",
      " 3/06\n",
      "86\n",
      "[英雄] Twitch - 戰前認知與出裝\n",
      "SamMa\n",
      " 3/07\n",
      "87\n",
      "[英雄] Teemo solo ATK Speed流\n",
      "shinytea\n",
      " 3/07\n",
      "88\n",
      "[英雄] Gangplank 爆擊型\n",
      "ideos\n",
      " 3/07\n",
      "86\n",
      "[英雄] Mord 本周有感\n",
      "cyberia\n",
      " 3/08\n",
      "87\n",
      "[分享]常用英文縮寫\n",
      "Alleyn\n",
      " 3/08\n",
      "88\n",
      "[英雄] Principle of Mage and Morgana Guide\n",
      "CKsincerity\n",
      " 3/09\n",
      "86\n",
      "[英雄] Warwick - Jungle流\n",
      "SamMa\n",
      " 3/09\n",
      "87\n",
      "[英雄] evelynn初體驗\n",
      "hawk7130\n",
      " 3/10\n",
      "88\n",
      "[觀念] 野外怪\n",
      "SamMa\n",
      " 3/10\n",
      "86\n",
      "[英雄] Warwick Jungle流(詳述1-6級)\n",
      "juige\n",
      " 3/10\n",
      "87\n",
      "[閒聊] Jungle or not?\n",
      "errard\n",
      " 3/10\n",
      "88\n",
      "[觀念] League of Legends 屬性解釋 (四)\n",
      "bigbite\n",
      " 3/12\n",
      "86\n",
      "[英雄] ap evelynn\n",
      "csyoyo\n",
      " 3/12\n",
      "87\n",
      "[創作] Amumu 哭哭木乃伊 簽名檔\n",
      "kent550079\n",
      " 3/13\n",
      "88\n",
      "[英雄] Katarina AD流分享\n",
      "iriself\n",
      " 3/15\n",
      "86\n",
      "[英雄] Twisted Fate 卡牌大師 AP流\n",
      "kraziyo\n",
      " 3/16\n",
      "87\n",
      "[英雄] Fiddlesticks - 稻草人 分享\n",
      "ahmin\n",
      " 3/16\n",
      "88\n",
      "[英雄] karthus  拋磚引玉版\n",
      "toofar1208\n",
      " 3/16\n",
      "86\n",
      "Re: [英雄] Malphite 分享\n",
      "h2901911\n",
      " 3/16\n",
      "87\n",
      "[知識] 自選Spell\n",
      "SamMa\n",
      " 3/17\n",
      "88\n",
      "[英雄] Karthus\n",
      "CKidy\n",
      " 3/17\n",
      "86\n",
      "[閒聊] survivability\n",
      "aded\n",
      " 3/17\n",
      "87\n",
      "[英雄] Corki，我輕輕地發動引擎，不帶走一條ꔠ…\n",
      "JohnLannan\n",
      " 3/17\n",
      "88\n",
      "Re: [知識] 自選Spell - 招喚者技能\n",
      "ETOHs\n",
      " 3/17\n",
      "86\n",
      "[英雄] veigar 人小本事大~\n",
      "i14d14\n",
      " 3/18\n",
      "87\n",
      "Re: [知識] 天賦\n",
      "p21077\n",
      " 3/18\n",
      "88\n",
      "Re: [英雄] veigar 人小本事大~\n",
      "enots\n",
      " 3/18\n",
      "86\n"
     ]
    }
   ],
   "source": [
    "from selenium import webdriver\n",
    "from selenium.webdriver.chrome.options import Options\n",
    "from bs4 import BeautifulSoup\n",
    "import time\n",
    "import os\n",
    "options= Options()\n",
    "options.add_argument('--headless')\n",
    "options.add_argument('--disable-gpu')\n",
    "driver=webdriver.Chrome(os.getcwd()+\"/chromedriver\",chrome_options=options)\n",
    "f=open(os.getcwd()+\"/data.txt\",'w',encoding='utf8')\n",
    "for i in range(1,3):\n",
    "    pagenumber=str(i)\n",
    "    driver.get('https://www.ptt.cc/bbs/LoL/index'+pagenumber+'.html')\n",
    "    time.sleep(0.5)\n",
    "    sourceCode=BeautifulSoup(driver.page_source,\"html.parser\")\n",
    "    articles=sourceCode.find_all(\"div\",\"r-ent\")\n",
    "    for article in articles:\n",
    "        sourceCode2=BeautifulSoup(str(article),\"html.parser\")\n",
    "        title=sourceCode2.find_all(\"div\",\"title\")[0].text\n",
    "        title=title.strip()\n",
    "        if title.startswith(\"[公告]\"):\n",
    "            pass\n",
    "        else:\n",
    "            date=sourceCode2.find_all(\"div\",\"date\")[0].text\n",
    "            number=sourceCode2.find_all(\"div\",\"nrec\")[0].text\n",
    "            author=sourceCode2.find_all(\"div\",\"author\")[0].text\n",
    "            print(title.strip())\n",
    "            print(author)\n",
    "            print(date)\n",
    "            number=number.replace(\"爆\",\">100\")\n",
    "            print(number)\n",
    "            data=title+\"\\n\"+number+\"\\n\"+author+\"\\n\"+date\n",
    "            f.write(data)\n",
    "f.close()\n",
    "driver.quit()\n",
    "        "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
